# permissions for end users to edit namespecials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespecial-editor-role
rules:
- apiGroups:
  - top.cwxstat.com
  resources:
  - namespecials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - top.cwxstat.com
  resources:
  - namespecials/status
  verbs:
  - get
