# permissions for end users to view namespecials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespecial-viewer-role
rules:
- apiGroups:
  - top.cwxstat.com
  resources:
  - namespecials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - top.cwxstat.com
  resources:
  - namespecials/status
  verbs:
  - get
